import { calculateMockStrokeRisk } from "./mockModel.js";

const RAW_FEATURE_KEYS = [
  "age",
  "hypertension",
  "heart_disease",
  "ever_married",
  "work_type",
  "avg_glucose_level",
  "bmi",
  "smoking_status"
];

function getPredictionObject(aiJson) {
  // Some APIs return { prediction: { ... } }, but this AI API returns
  // { stroke_probability, threshold, prediction: 1, risk_label, ... }.
  // If prediction is only a number, we must use the root object instead.
  if (aiJson?.prediction && typeof aiJson.prediction === "object") {
    return aiJson.prediction;
  }

  if (aiJson?.data && typeof aiJson.data === "object") {
    return aiJson.data;
  }

  if (aiJson?.result && typeof aiJson.result === "object") {
    return aiJson.result;
  }

  return aiJson ?? {};
}

function toNumber(value, fallback = 0) {
  const numberValue = Number(value);
  return Number.isFinite(numberValue) ? numberValue : fallback;
}

function normalizeRiskLevel(value, probabilityPercent) {
  if (typeof value === "string" && value.trim()) {
    const normalized = value.toLowerCase();

    if (normalized.includes("high")) return "High Risk";
    if (normalized.includes("medium") || normalized.includes("moderate")) return "Medium Risk";
    if (normalized.includes("low")) return "Low Risk";

    return value;
  }

  if (probabilityPercent >= 70) return "High Risk";
  if (probabilityPercent >= 35) return "Medium Risk";
  return "Low Risk";
}

function normalizeAiResult(aiJson) {
  const predictionData = getPredictionObject(aiJson);

  const rawProbability =
    predictionData.stroke_probability ??
    predictionData.strokeProbability ??
    predictionData.probability ??
    predictionData.risk_score ??
    predictionData.riskScore ??
    predictionData.percentage ??
    predictionData.probabilityPercent ??
    0;

  let probabilityPercent = toNumber(rawProbability, 0);

  // AI returns 0.428..., frontend/backend should show 42.8%
  if (probabilityPercent <= 1) {
    probabilityPercent *= 100;
  }

  probabilityPercent = Math.min(Math.max(probabilityPercent, 0), 100);
  probabilityPercent = Math.round(probabilityPercent * 100) / 100;

  const riskLevel = normalizeRiskLevel(
    predictionData.risk_label ??
      predictionData.riskLabel ??
      predictionData.riskLevel ??
      predictionData.risk_level ??
      predictionData.label ??
      predictionData.classification,
    probabilityPercent
  );

  const recommendations =
    Array.isArray(predictionData.recommendations) && predictionData.recommendations.length > 0
      ? predictionData.recommendations
      : [
          "This result is generated by the AI model endpoint.",
          "This screening result is not a medical diagnosis.",
          "Please consult a healthcare professional for medical decisions."
        ];

  return {
    probabilityPercent,
    riskLevel,
    factors: Array.isArray(predictionData.factors) ? predictionData.factors : [],
    recommendations,
    disclaimer:
      predictionData.disclaimer ??
      "This is an AI-assisted screening result, not a medical diagnosis.",
    rawAiResponse: aiJson
  };
}

function buildAiPayload(input) {
  const rawFeatures = {};

  for (const key of RAW_FEATURE_KEYS) {
    rawFeatures[key] = input[key];
  }

  return {
    mode: "raw",
    raw_features: rawFeatures
  };
}

export async function getPrediction(input) {
  const aiApiUrl = process.env.AI_API_URL;

  if (!aiApiUrl) {
    return {
      modelSource: "mock-backend-placeholder",
      modelVersion: "mock-v1",
      prediction: calculateMockStrokeRisk(input)
    };
  }

  try {
    const response = await fetch(aiApiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(buildAiPayload(input))
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`AI API returned status ${response.status}: ${errorText}`);
    }

    const aiJson = await response.json();

    return {
      modelSource: "ai-api",
      modelVersion: process.env.AI_MODEL_VERSION || "ai-api-v1",
      prediction: normalizeAiResult(aiJson)
    };
  } catch (error) {
    return {
      modelSource: "mock-fallback-ai-unavailable",
      modelVersion: "mock-v1",
      prediction: {
        ...calculateMockStrokeRisk(input),
        warning: `AI API was unavailable, so backend used mock prediction. Reason: ${error.message}`
      }
    };
  }
}